disabled_rules:
  - cyclomatic_complexity
  - line_length
  - todo
  - unused_optional_binding
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - implicit_return
  - let_var_whitespace
  - literal_expression_end_indentation
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - redundant_nil_coalescing
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rule configurations
nesting:
  type_level:
    warning: 2
