language: objective-c
osx_image: xcode9.2
git:
  depth: 1

before_script:
# Set up mock API server
- cd ..
- git clone git://github.com/minhtule/PredictionIO-Mock-Server.git --depth 1
- cd PredictionIO-Mock-Server
- npm install
- node app.js &
- sleep 3  # Give mock server some time to bind to sockets, etc
- cd ../PredictionIO-Swift-SDK

script:
# Check Podspec
- pod lib lint

- set -o pipefail

# Test the SDK on iOS
- xcodebuild -workspace PredictionIO.xcworkspace -scheme "PredictionIO iOS" -destination "OS=11.2,name=iPhone X" ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty

# Build the SDK on OS X
# - xcodebuild -workspace PredictionIO.xcworkspace -scheme "PredictionIO OSX SDK" -sdk macosx -destination "platform=OS X,arch=x86_64" ONLY_ACTIVE_ARCH=NO build | xcpretty

# Build the iOS demo app
# - xcodebuild -workspace PredictionIO.xcworkspace -scheme "iOS Example" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO build | xcpretty
